CREATE TABLE OPERATORS
(
OPERATOR_ID NUMBER PRIMARY KEY,
OPERATOR_NAME VARCHAR2(500)
);

CREATE TABLE BUS_TYPES
(
BUS_TYPE_ID NUMBER PRIMARY KEY,
BUS_TYPE_NAME VARCHAR2(50)
);

CREATE TABLE BUSES
(
BUS_ID NUMBER PRIMARY KEY,
BUS_NO VARCHAR2(100),
CAPACITY NUMBER,
BUS_TYPES  NUMBER,
OPERATOR_ID VARCHAR2(100),
CONSTRAINTS FKON FOREIGN KEY(OPERATOR_ID) REFERENCES OPERATORS(OPERATOR_ID),
CONSTRAINTS FKBT FOREIHN KEY(BUS_TYPES) REFERENCES BUS_TYPES(BUS_TYPE_ID)
);

CREATE TABLE ADMIN_DETAILS
(
ADMIN_ID NUMBER PRIMAR KEY,
ADMIN_NAME VARCHAR2(100),
ADMIN_PHNO NUMBER,
ADMIN_EMAIL VARCHAR2(100),
OPERATOR_ID NUMBER ,
CONSTRIANTS OPID FOREIGNK KEY(OPERATOR_ID) REFERENCES OPERATORS(OPERATOR_ID)
);

CREATE TABLE ADMIN_TRACK
(
ADMIN_TRACK_ID NUMBER PRIMARY KEY,
ADMIN_ID NUMBER ,
OPERATOR_ID  NUMBER ,
LOGIN_DATE DATE,
LOGIN_TIME TIMESTAMP,
CONSTRIANTS ADID FOREIGNK KEY(ADMIN_ID) REFERENCES ADMIN_DETAILS(ADMIN_ID)
);

CREATE TABLE BUS_ROUTE 
(
BUS_ROUTE_ID NUMBER PRIMARY KEY,
START_LOCATION VARCHAR2(150),
END_LOCATION VARCHAR2(150)
);

CREATE TABLE SEAT_AVAILABLITY
(
SEAT_AVL_ID NUMBER PRIMARY,
BUS_ID NUMBER,
SEAT_AVAL NUMBER,
BOOKED_SEATS,
CONSTRIANTS FKBID FOREIGN KEY(BUS_ID) REFERENCES BUSES(BUS_ID)
);

CREATE TABLE SCHEDULED_TIME_FOR_BUSES
(
SCHED_ID NUMBER PRIMARY KEY,
BUS_ID NUMBER,
ROUTE_ID NUMBER,
JOURNEY_DATE DATE,
DEPART_TIME VARCHAR2(50),
ARRAIV_TIME VARCHAR2(50),
BUS_FARE_ROUTE NUMBER,
CONSTRAINTS BFK FOREIGN KEY(BUS_ID) REFERENCES BUSES(BUS_ID),
CONSTRAINTS RFK FOREIGN KEY(ROUTE_ID) REFERENCES BUS_ROUTE(BUS_ROUTE_ID)
);

CREATE TABLE PASSENGER
(
PASSENGER_ID NUMBER PRIMARY KEY,
NAME VARCHAR2(100),
AGE NUMBER,
GENDER VARCHAR2(50),
CONTACT_NUMBER NUMBER
);

CREATE TABLE BUS_BOOKING
(
BOOKING_ID NUMBER PRIMARY KEY,
BUS_ID NUMBER,
PRIMARY_PASSENGER_ID NUMBER,
BOOKING_DATE DATE,
NO_OF_TICKET NUMBER,
STATUS VARCHAR2(50),
CONSTRAINTS BBID FOREIGN KEY(BUS_ID) REFERENCES BUSES(BUS_ID),
CONSTRIANTS PIDFK FOREIGN KEY(PRIMARY_PASSENGER_ID) REFERENCES PASSENGER(PASSENGER_ID)
);

CREATE TABLE BOOKING_PASSENGER_DETAILS
(
BOOKING_PASSENGER_ID NUMBER PRIMARY KEY,
BOOKING_ID NUMBER,
BUS_ID NUMBER,
PASSENGER_ID NUMBER,
SEAT_NUMBER VARCHAR2(50),
CONSTRAINTS BPD FOREIGN KEY(BUS_ID) REFERENCES BUSES(BUS_ID),
CONSTRAINTS BKID FOREIGN KEY(BOOKING_ID) REFERENCES BUS_BOOKING(BOOKING_ID),
CONSTRAINTS PSID FOREIGN KEY(PASSENGER_ID) REFERENCES PASSENGER(PASSENGER_ID)
);

CREATE TABLE BOOKING_PAYMENT
(
PAY_ID NUMBER PRIMAR KEY,
BOOKING_ID NUMBER,
PAY_TYPE VARCHAR2(100),
AMOUNT NUMBER,
PAY_DATE DATE,
PAY_TIME TIMESTAMP,
CONSTRAINTS BOKID FOREIGN KEY(BOOKING_ID) REFERENCES BUS_BOOKINGS(BOOKING_ID)
);

INSERT INTO OPERATORS VALUES(1,'SRM TRAVEL');
INSERT INTO OPERATORS VALUES(2,'KINGS TRAVEL');
INSERT INTO OPERATORS VALUES(3,'MRS TRAVEL');

INSERT INTO BUS_TYPES VALUES(1,'AC_SLEEPER');
INSERT INTO BUS_TYPES VALUES(2,'NON_AC_SLEEPER');
INSERT INTO BUS_TYPES VALUES(3,'SEMISLEEPER');
INSERT INTO BUS_TYPES VALUES(4,'AC_SEATER');


INSERT INTO BUSES VALUES(100,'TNAB11',10,1,1);
INSERT INTO BUSES VALUES(101,'TNAB12',10,2,1);
INSERT INTO BUSES VALUES(102,'TNAB13',10,3,1);
INSERT INTO BUSES VALUES(103,'TNAB14',10,4,1);
INSERT INTO BUSES VALUES(104,'TNAB21',10,1,2);
INSERT INTO BUSES VALUES(105,'TNAB22',10,3,2);
INSERT INTO BUSES VALUES(106,'TNAB31',10,2,3);
INSERT INTO BUSES VALUES(107,'TNAB32',10,3,3);

INSERT INTO BUS_ROUTE VALUES(200,'THANJAVUR','CHENNAI');
INSERT INTO BUS_ROUTE VALUES(201,'CHENNAI','THANJAVUR');
INSERT INTO BUS_ROUTE VALUES(202,'THANJAVUR','COIMBATORE');
INSERT INTO BUS_ROUTE VALUES(203,'COIMBATORE','THANJAVUR');
INSERT INTO BUS_ROUTE VALUES(204,'THANJAVUR','KOCHI');
INSERT INTO BUS_ROUTE VALUES(205,'KOCHI','THANJAVUR');
INSERT INTO BUS_ROUTE VALUES(206,'KUMBAKONAM','CHENNAI');
INSERT INTO BUS_ROUTE VALUES(207,'CHENNAI','KUMBAKONAM');
INSERT INTO BUS_ROUTE VALUES(208,'THANJAVUR','BANGALORE');
INSERT INTO BUS_ROUTE VALUES(209,'BANGALORE','THANJAVUR');

CREATE SEQUENCE SQADMIN  START WITH 1550 INCREMENT BY 1 ORDER;

CREATE SEQUENCE SQATID START WITH 1000 INCREMENT BY 1 NOMAXVALUE ORDER;

CREATE SEQUENCE SQSCHEDID START WITH 300 INCREMENT BY 1 NOMAXVALUE ORDER;

CREATE SEQUENCE SQBKID START WITH 400 INCREMENT BY 1 NOMAXVALUE ORDER;

CREATE SEQUENCE SQSAT START WITH 800 INCREMENT BY 1 NOMAXVALUE ORDER;

CREATE SEQUENCE SQBIDD START WITH 500 INCREMENT BY 1 NOMAXVALUE ORDER;

CREATE SEQUENCE SQBPAY START WITH 600 INCREMENT BY 1 NOMAXVALUE ORDER;

CREATE OR REPLACE TYPE PASSENGERRECORD AS OBJECT(NAME VARCHAR2(100),AGE NUMBER,GENDER CHAR(1),CONTACT_NUMBER NUMBER,IS_PRIMARY CHAR(1));

CREATE OR REPLACE TYPE PASSENGERTABLE AS TABLE OF PASSENGERRECORD; 

CREATE OR REPLACE TYPE SEAT_NO AS TABLE OF VARCHAR2(100);