create or replace TRIGGER ADMIN_TRACK AFTER INSERT OR UPDATE ON SCHEDULED_TIME_FOR_BUSES FOR EACH ROW
DECLARE
PRAGMA AUTONOMOUS_TRANSACTION;
BID NUMBER;
BEGIN
IF ADMIN_CONTEXT_PKG.G_ADMIN IS NOT NULL THEN

INSERT INTO ADMIN_TRACK(ADMIN_TRACK_ID,ADMIN_ID,LOGIN_DATE,LOGIN_TIME)
VALUES(SQATID.NEXTVAL,ADMIN_CONTEXT_PKG.G_ADMIN,SYSDATE,SYSTIMESTAMP);
COMMIT;
ELSE
RAISE_APPLICATION_ERROR(25468,'ADMIN_ID is not set. Trigger cannot proceed');
END IF;
END;
/

create or replace TRIGGER TRGINSERT BEFORE INSERT OR UPDATE OF CREATED_BY,CREATED_ON ON DETAILS FOR EACH ROW
BEGIN
IF :NEW.CREATED_BY IS NULL THEN
:NEW.CREATED_BY:='ADMIN';
END IF;
IF :NEW.CREATED_ON IS NULL THEN
:NEW.CREATED_ON:=SYSDATE;
END IF;
END;
/